import type { LoginView } from '../../../shared/vault-contract'

export function makeLoginView(overrides: Partial<LoginView> = {}): LoginView {
  return {
    id: 'item-id',
    type: 'login',
    name: 'Sample item',
    subtitle: 'Sample subtitle',
    username: 'sample-user',
    uri: 'https://example.invalid',
    uris: [{ uri: 'https://example.invalid', match: null }],
    hasTotp: false,
    passkeyCount: 0,
    passwordHistoryCount: 0,
    attachmentCount: 0,
    folderId: null,
    favorite: false,
    usageCount: 0,
    lastUsedAt: null,
    createdAt: '2026-07-16T00:00:00.000Z',
    updatedAt: '2026-07-16T00:00:00.000Z',
    deletedAt: null,
    archivedAt: null,
    reprompt: 0,
    passwordUpdatedAt: null,
    notes: null,
    passkeys: [],
    customFields: [],
    attachments: [],
    cardholderName: '',
    brand: '',
    expMonth: '',
    expYear: '',
    title: '',
    firstName: '',
    middleName: '',
    lastName: '',
    address1: '',
    address2: '',
    address3: '',
    city: '',
    state: '',
    postalCode: '',
    country: '',
    company: '',
    email: '',
    phone: '',
    identityUsername: '',
    publicKey: '',
    fingerprint: '',
    ...overrides
  }
}
